set-option -g status-position top
set -g mouse on

# set -g automatic-rename-format '#(basename #{pane_current_path})'
# set -g status-interval 5

set -g window-status-format '#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#(pwd="#{pane_current_path}"; echo ${pwd####*/}) #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]'
set -g window-status-current-format '#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#(pwd="#{pane_current_path}"; echo ${pwd####*/}) #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]'
set -g window-status-separator ""
set -g pane-border-status top
set -g pane-border-format '#{pane_index} #{pane_current_path}'

# bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
# bind-key -T copy-move-vi WheenDownPane send-keys -X scroll-down

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @continuum-restore 'on'

# set -g @plugin "arcticicestudio/nord-tmux"
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'tmux-plugins/tmux-continuum'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
